apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-artifacts-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      volumes:
        - name: mlflow-data
          persistentVolumeClaim:
            readOnly: false
            claimName: mlflow-data-pvc
        - name: mlflow-artifacts
          persistentVolumeClaim:
            readOnly: false
            claimName: mlflow-artifacts-pvc
      containers:
        - name: mlflow
          image: ${ACR_NAME}.azurecr.io/${ACR_IMAGE_NAME}:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: mlflow-data
              mountPath: mlruns
            - name: mlflow-artifacts
              mountPath: mlartifacts
          resources:
            limits:
              cpu: 1
              memory: 1Gi
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: mlflow
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mlflow-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mlflow-deployment
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
